### ISSUE TITLE
webforms现在是否已经可以用于正式生产环境

### ISSUE THREAD

**Issue by nuintun** [webforms/webforms#15]
如题，完成度有多少了？

**Comment by hotoo** [comment]
通用校验器 (https://github.com/webforms/univ) 已经使用在生产环境中。浏览器端的 webforms 基于 univ，但是目前还没有完成。

**Comment by nuintun** [comment]
Good，我去看看，3Q~ 希望webforms尽快出正式版吧，arale的validator不太好用！
