### ISSUE TITLE
参考

### ISSUE THREAD

**Issue by hotoo** [webforms/webforms#8]
- [Mootools: Form.Validator](http://mootools.net/docs/more/Forms/Form.Validator)
- [JavaScript Form Validation : quick and easy!](http://www.javascript-coder.com/html-form/javascript-form-validation.phtml)
- [validate.js](https://github.com/rickharrison/validate.js)
- [jQuery Validation Plugin](http://jqueryvalidation.org/documentation/)
- [Validatious 2.0](http://validatious.org/)

---
- http://www.comsharp.com/GetKnowledge/zh-CN/It_News_K745.aspx
- http://html5forwebdesigners.com/forms/index.html

---
- http://www.whatwg.org/specs/web-apps/current-work/#dom-cva-validationmessage
- http://www.whatwg.org/specs/web-apps/current-work/multipage/
- http://tools.ietf.org/html/rfc3339
- http://dev.w3.org/html5/markup/input.date.html
- http://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format
- http://www.west-wind.com/weblog/posts/2012/Nov/08/HTML5-Input-typedate-Formatting-Issues

**Comment by lizzie** [comment]
## jQuery Validator

https://github.com/jzaefferer/jquery-validation , 目前 jQuery 社区里写的一个校验插件.

特点:
- 校验整个表单;
- 校验某个表单项;
- 重置表单;
- 自定义 Selector, `:blank, :filled, :unchecked`;
- method 和 rules 两个概念, method 为校验方法, 只有一个条件. 而 rules 是 method 的组合, 称为元素的校验规则;
- 错误处理;
  - 普通的信息显示;
  - 错误元素获焦;
- class 作为规则特殊处理;
- 校验触发事件是在 submit 之后, keyup, 或者 blur
- 不支持一个页面多表单校验

## validate.js

http://rickharrison.github.io/validate.js/ 超精简, 基本上下面的代码就已覆盖他提供的所有功能了. 
有自定义规则, 使用也很简单:

``` js
var validator = new FormValidator('example_form', [{
    name: 'req',
    display: 'required',    
    rules: 'required'
}, {
    name: 'alphanumeric',
    rules: 'alpha_numeric'
}, {
    name: 'password',
    rules: 'required'
}, {
    name: 'password_confirm',
    display: 'password confirmation',
    rules: 'required|matches[password]'
}], function(errors, event) {
    if (errors.length > 0) {
        // Show the errors
    }
});
```

rules 可以组合, 但最大的问题, 是没法异步校验. 每个规则的检测都是同步的返回 true or false.

## JavaScript Form Validation : quick and easy!

功能和 validator.js 差不多, 代码比较旧. 通过 `addValidation` 添加每个校验项, 还不如 validator.js 的简洁. 这个就不多说了.

## Mootools 的 Form.Validator

http://mootools.net/docs/more/Forms/Form.Validator

除  jQuery Validator 的所有点外:
- stop/start, 可中途停止/中途继续校验
- ignoreField/enforceField, 忽略/强制校验某项
- add(name, options)/addAllThese([]), 添加校验规则
- 事件: formValidate, elementValidate, elementPass, elementFail
- 规则可在 DOM 元素上通过 data-validators="xxx" 定义
- 支持多语言

## Validatious 2.0

最特殊的一点是 `validate( "email".is("required").andIsAn("email") );` 校验规则的书写符合人类阅读习惯. 比较喜欢这样的方式. 

居然 500, 没法打开细看...囧rz

## KISSY Validation

https://github.com/kissyteam/kissy-gallery/tree/1128b72b7f56d80aac9eba23035afa8b5adc9648/gallery/validation

前同事写的一个. 
- 规则可在 DOM 元素上通过 data-valid="{required:false,fiter:['gif,jpg','只允许的格式为{0}']}" 定义
- 异步校验通过关键词 remote 来定义
- 配置项很多, 估计是想涵盖所有的场景,

**Comment by hotoo** [comment]
@lizzie 赞 :)
