### ISSUE TITLE
required 的输入字段是否应该先 trim？

### ISSUE THREAD

**Issue by hotoo** [webforms/webforms#9]
很多场景中，required 输入框实际要求是不允许输入空白内容。

现在考虑以下 2种方案：
1. 对 required 字段进行 trim。这个会导致允许输入空白内容的情况出现问题。
2. 新增 nonblank 规则。

想听听大家的想法。

**Comment by lizzie** [comment]
trim 吧. 如果某项是必填的. 空白内容本身就是无效的. 我的理解. 必填的内容肯定是有效的内容, 空白字符没意义.

**Comment by pierrewrs** [comment]
trim +1
提交前的数据都应该做trim操作啊 
不会有允许输入空白内容的情况出现的 没意义

**Comment by hotoo** [comment]
还是需要区分表单字段类型：
- 密码框：无论输入什么内容，都不允许 trim。
- 输入框：目前考虑 trim 方案。
- 单行选择框：目前考虑 trim 方案。
- 多行选择框：判断选择的个数，而不是内容。
- 复选框：判断 checked 个数。
